backend:
  name: git-gateway
  branch: main
media_folder: public/assets/images/blog
public_folder: /assets/images/blog
site_url: 'https://ggbengsite.netlify.app'
collections:
  - name: posts
    label: Blog Posts
    label_singular: Blog Post
    folder: src/pages/blog/posts
    create: true
    delete: true
    fields:
      - { name: title, widget: string, label: Post Title }
      - {
          name: pubDate,
          widget: datetime,
          format: YYYY/MM/DD,
          date_format: YYYY/MM/DD,
          time_format: false,
          label: PubDate,
        }
      - {
          name: description,
          widget: string,
          label: Description,
          required: false,
        }
      - {
          label: FeaturedImage,
          name: featuredImage,
          widget: image,
          required: true,
        }
      - { label: Tags, name: tags, widget: list }
      - { name: body, widget: markdown, label: Post Body }
      - {
          label: Layout,
          name: layout,
          widget: hidden,
          default: ../../../layouts/Post.astro,
        }
